apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-template-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-template-demo
  template:
    metadata:
      labels:
        app: helm-template-demo
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.app.logLevel }}
