apiVersion: v1
kind: Service
metadata:
  name: ss-demo-headless
  labels:
    app: ss-demo
spec:
  clusterIP: None
  selector:
    app: ss-demo-wrong
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ss-demo
  labels:
    app: ss-demo
spec:
  serviceName: ss-demo-headless
  replicas: 1
  selector:
    matchLabels:
      app: ss-demo
  template:
    metadata:
      labels:
        app: ss-demo
    spec:
      containers:
        - name: app
          image: local/k8s-debug-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
