apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-upgrade-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-upgrade-demo
  template:
    metadata:
      labels:
        app: helm-upgrade-demo
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
