apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-demo
  labels:
    app: ingress-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-demo
  template:
    metadata:
      labels:
        app: ingress-demo
    spec:
      containers:
        - name: app
          image: local/k8s-debug-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-demo
  labels:
    app: ingress-demo
spec:
  selector:
    app: ingress-demo
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-demo-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lVUUpvQU4rMUZaRWpHTTNxZWNQRHpScWRwTFFzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dURVhNQlVHQTFVRUF3d09ZWEJ3TG1SbGJXOHViRzlqWVd3d0hoY05Nall3TlRJeE1UYzBNakV4V2hjTgpNamN3TlRJeE1UYzBNakV4V2pBWk1SY3dGUVlEVlFRRERBNWhjSEF1WkdWdGJ5NXNiMk5oYkRDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUtqem9SWFc4MFhQRlRuL3p6SlZWcW00SmgzMzIyZzkKUzUyQXNlTTZYTzZlUS92WWZyQTFPaURhdy95Z25WWUYrZlFyeE9ieFZIUzQ5czB2RFExV3dBd29odE5GUEI5SQpKWE54OUZDZlR6NEl6RHZCc1JjWGdjc0ZOQ3NFWnd1TVVHREVCMm5LY05EUSt6VDlsRTdEcnJ5WHAzTjIveXVTCnhIL290WG9NVDMwdVZPSVVQUFdyTkIwa1hGalFkWm8zRGoyNG8yUzl5TjMzUmw3ZWVlOUtvSUUzb3VUMWRaN24KamxMNjhCdkNvY08wYXFYa3c0WG5hbStzL0djY1BrRTBIZThlOEdvcCtOMXhOR05sM0dVdjV5Y0wxeGVKV2tsSQpmcmZHS3lnRExKN29ETGtkSEFSSDhGaktEOXdaWUs3aitYRjN0MC9Uci9FSU1NVWIwY2d2bERVQ0F3RUFBYU5UCk1GRXdIUVlEVlIwT0JCWUVGRk40Q0Fablc5RjQ3aEVRejNFRXpEcExmaVZ0TUI4R0ExVWRJd1FZTUJhQUZGTjQKQ0Fablc5RjQ3aEVRejNFRXpEcExmaVZ0TUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFKMkdOeUdWUnpLMVJpbklxd1RlN3VRZlhPb2RTaTROdVR0UStWU2NuNjRiY2d4amN0UmFWL1p4CmZaU2tnR3crN1c0NDdNT2VxdE1aUnNlMUQ1aHlnSzV6ZXkwQ1FwOWZnVTlPV3NkWURQWmZhaElTaHMvcVlLVkgKdlFxM3Nvc3VCbmh5UWtMZDcycG9POXN1YitDejRYaEpnNnhFRTVGcytTa0g0VlRTcEtUbEkrU2h3MVordHFXZgpQM2VvVzNMUmtLdFd6eXNZelBIdzF0a0RFNDIyV2p3bDdSbjVsOFVWcVNRRTdjMGlTcVZmY0NGWUdvL2dLMVN4CmpUZS92bkszaTJ2Ynp6Q3MzRVBzVlAxbFlwMUlzU0VBNlFxRUVjT3FGK0c3YUREYlh3SkJFbTdtUDBaRmhoaTUKTk1EaExmNzNWbjFGVkNxdjlpMUpMZGo3NUdRMnd0az0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ284NkVWMXZORnp4VTUKLzg4eVZWYXB1Q1lkOTl0b1BVdWRnTEhqT2x6dW5rUDcySDZ3TlRvZzJzUDhvSjFXQmZuMEs4VG04VlIwdVBiTgpMdzBOVnNBTUtJYlRSVHdmU0NWemNmUlFuMDgrQ013N3diRVhGNEhMQlRRckJHY0xqRkJneEFkcHluRFEwUHMwCi9aUk93NjY4bDZkemR2OHJrc1IvNkxWNkRFOTlMbFRpRkR6MXF6UWRKRnhZMEhXYU53NDl1S05rdmNqZDkwWmUKM25udlNxQ0JONkxrOVhXZTU0NVMrdkFid3FIRHRHcWw1TU9GNTJwdnJQeG5IRDVCTkIzdkh2QnFLZmpkY1RSagpaZHhsTCtjbkM5Y1hpVnBKU0g2M3hpc29BeXllNkF5NUhSd0VSL0JZeWcvY0dXQ3U0L2x4ZDdkUDA2L3hDRERGCkc5SElMNVExQWdNQkFBRUNnZ0VBSHMyQVRuZUlsZThwNncraENvZTFpNjdud0NuNnhoZjZ5OFgxYUx5d3ljNXcKRGFBTWhQckhWTXNkMVZiQktMaGhPR3VzZEFDR3lkc1pJQktXZWhxWlcvNGRpckpDUWwvSWVESkwvVkQyUlJTYwppNzZHRjNReE5UOEhJbHFrb04zZG42N052VE5yK3g1RzFvUHZBS2M3bWVXNllWcE9MbmNOUFZiRGszTmdJSzNBClQ5OVo1dFQxMCtFUnlyNkNYZUdxa01rWmxVdGY1bWZObGQ2czg3L2h4dTJIN1VVaUZqeVZ2SjRaS3FiK3JiQVMKUkdzdzBmYWFyN0tCaTBxcERtcTlMVUxOclNXZ0Q0aXhIVGIxb3JYdGMzTk9EUi9JQ2hoaVg1OHErbjBJZmRWdgpBNTczT1EvSFVOQnphUzY0enhqMXphOUdjSURnSURCZmJiYVlkY3FlNXdLQmdRRGRWWUhCaUxXVk9hM2NFdzlSClRRVXV0NER2TUl3alYvYmxybExZWmtVTXBLdFJGRkJCdWFFRGRUaGw2aEpnNHExaUhsdEFsZFEwL01EMWNxOHcKcEczZkVYQWg3L0RFZ01OM1VmNHp0Tk9wSWN4aEhaTHNLM3ZwdVU0bGlnL0JYdzFDeHZWWDhBaVVBdFh1NVdMegppbklLT1RZeGxCT3MrcHlySUpPM0NmTDdqd0tCZ1FERGFkUGR3TWN6Q1g2MnlFclJmQVRobFFlVjVtdktacXhoClMrcCt5UGdXL1FMMFdmcm9LN1VlY0hPZjJZVWVCQ05laFNDeG9ZS1lleGR6ZDZ4QzBnZ0U2UnBhSTZNdUpURkcKb1lxOFB4MmFHK1pQYVpUS3A2UHRucHg1ay9kbmk3T2w2d3JtRWRrTC8rb3BRMTZTZUJWbW1TdnBqdnhpb0FYSQpGS1pQZG1LaCt3S0JnRHdBM1YrQlYzRHdKU0VmamF5Rnk5emhaTFB6bmxwS2s2V3F2OHpvMU5sYm54SXBCcVQ2CjFScmg0WHRIbk5ubE9nbjZudFNBaWZvZmQ1UlRGZ21DMmtKNk1NTVNrRnhGYURobDR4dFRiM3BQcmwrNXE4WVkKOTh2aUw3eGZsR3ZnLy9CVmpkZmNQQWNjU2JFdFFNa3poRDBmUzREZld3SXZJdUFGd2VZQ2JYd2pBb0dBVkU3dApSSWd1cVR0WWV4MnhBZTVpNEx4K2VGTGdnSU9KcmJTbUtDc210aXhVd1AydFBjdlZxWnRVbDB1dW5nT2xDdHVlCi9tUXpSdndjWXdubnZUQ0dteS9DMmM3MFVTMWt0QmR3RnNXWVRPdnFrcXAzc25OZlMxNmFIZTRUMkkyeVpVd2gKK0o4TXFKdXgrRG1Eck9lNE8vcXJzbW1wUkJmTVJzVjU5MkNaTDA4Q2dZQlN1aTR0eHcrRzFMZWNwRmNMVDFNYwpGWm8rUU9YaWdhalRxNzdrN1d6enorbUw3Wk9rc05PYXRjaXFMVlNWTHFPUmozZ2F4NFlNRU9jbTFNL2FaMWtJClZpaTJXeVVCcjh3WkQrQlU4WmVyYjJmbEZqam9KcDdZWm11cy9ETUhRQm1iYnlvb081ZjVlZXZPMGl6RGtqNlgKeWYybmNmWmdKb0NWZ0c1SElXeVBPUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-demo
  labels:
    app: ingress-demo
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.demo.local
      secretName: demo-tls
  rules:
    - host: app.demo.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ingress-demo
                port:
                  number: 80
