apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdb-demo
  labels:
    app: pdb-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdb-demo
  template:
    metadata:
      labels:
        app: pdb-demo
    spec:
      containers:
        - name: app
          image: local/k8s-debug-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-demo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pdb-demo
