apiVersion: apps/v1
kind: Deployment
metadata:
  name: hook-lifecycle-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hook-lifecycle-demo
  template:
    metadata:
      labels:
        app: hook-lifecycle-demo
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
