apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-demo
  labels:
    app: affinity-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: affinity-demo
  template:
    metadata:
      labels:
        app: affinity-demo
    spec:
      nodeSelector:
        disktype: ssd
      containers:
        - name: app
          image: local/k8s-debug-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
