apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrong-cmd-demo
  labels:
    app: wrong-cmd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrong-cmd-demo
  template:
    metadata:
      labels:
        app: wrong-cmd-demo
    spec:
      containers:
        - name: app
          image: local/k8s-debug-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c", "run-app"]
