name: 09 Environment Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Specific Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.0' # Or read from .nvmrc via node-version-file
          cache: 'npm'
          
      - name: Verify Version
        run: node -v
